// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp-j6dIeZP_C2PtPUsPO5v_-Qmsr_eoKs',
    appId: '1:195982060113:web:363b75296d8033b482e670',
    messagingSenderId: '195982060113',
    projectId: 'liger-scooter-data-collection',
    authDomain: 'liger-scooter-data-collection.firebaseapp.com',
    storageBucket: 'liger-scooter-data-collection.appspot.com',
    measurementId: 'G-F4R1RF21ST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUFgwyHDNVlE0pa1XpYaNJODTtgeoaxaQ',
    appId: '1:195982060113:android:b7e20a689850699882e670',
    messagingSenderId: '195982060113',
    projectId: 'liger-scooter-data-collection',
    storageBucket: 'liger-scooter-data-collection.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClQPOQRGBvsl2XvFFehtMqV-_48bhTqOU',
    appId: '1:195982060113:ios:864eeff37999bac682e670',
    messagingSenderId: '195982060113',
    projectId: 'liger-scooter-data-collection',
    storageBucket: 'liger-scooter-data-collection.appspot.com',
    iosBundleId: 'com.example.ligerScooterDataCollectionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClQPOQRGBvsl2XvFFehtMqV-_48bhTqOU',
    appId: '1:195982060113:ios:864eeff37999bac682e670',
    messagingSenderId: '195982060113',
    projectId: 'liger-scooter-data-collection',
    storageBucket: 'liger-scooter-data-collection.appspot.com',
    iosBundleId: 'com.example.ligerScooterDataCollectionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp-j6dIeZP_C2PtPUsPO5v_-Qmsr_eoKs',
    appId: '1:195982060113:web:de72eb6b8e580d7382e670',
    messagingSenderId: '195982060113',
    projectId: 'liger-scooter-data-collection',
    authDomain: 'liger-scooter-data-collection.firebaseapp.com',
    storageBucket: 'liger-scooter-data-collection.appspot.com',
    measurementId: 'G-K33RYLM1KP',
  );
}
